/**
 * @file lipsum/core/version.hpp
 *
 * @brief Version constants for lipsum-cpp
 *
 * This defines constants for the current lipsum-cpp version. It is
 * automatically generated by a CMake script. This file is under the BSD
 * Zero-Clause License.
 *
 * @copyright Copyright (c) 2026 LambBread
 *
 * @author LambBread from github.com
 */
#pragma once

#ifndef LIPSUM_CORE_VERSION_HPP
#    define LIPSUM_CORE_VERSION_HPP

/**
 * @brief The current version of lipsum-cpp.
 *
 * @since 0.2.1
 *
 * This constant stores the current version of lipsum-cpp, stored as a string.
 */
inline constexpr const char* LIPSUM_CPP_VERSION = "0.4.2";

/**
 * @brief The major version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current major version of lipsum-cpp.
 */
inline constexpr int LIPSUM_CPP_VERSION_MAJOR = 0;

/**
 * @brief The minor version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current minor version of lipsum-cpp.
 */
inline constexpr int LIPSUM_CPP_VERSION_MINOR = 4;

/**
 * @brief The patch version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current patch version of lipsum-cpp.
 */
inline constexpr int LIPSUM_CPP_VERSION_PATCH = 2;
#endif
