/**
 * @file lipsum/core/version.hpp
 *
 * @brief Version constants for lipsum-cpp
 *
 * This defines constants for the current lipsum-cpp version. It is
 * automatically generated by a CMake script. This file is under the BSD
 * Zero-Clause License.
 *
 * @copyright Copyright (c) 2026 LambBread
 *
 * @author LambBread from github.com
 */
#pragma once

#ifndef LIPSUM_CORE_VERSION_HPP
#    define LIPSUM_CORE_VERSION_HPP

/**
 * @brief The current version of lipsum-cpp.
 *
 * @since 0.2.1
 *
 * This constant stores the current version of lipsum-cpp, stored as a string.
 */
inline constexpr const char* LIPSUM_CPP_VERSION = "0.4.4";

/**
 * @brief The current major version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current major version of lipsum-cpp.
 */
inline constexpr int LIPSUM_CPP_VERSION_MAJOR = 0;

/**
 * @brief The current minor version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current minor version of lipsum-cpp.
 */
inline constexpr int LIPSUM_CPP_VERSION_MINOR = 4;

/**
 * @brief The current patch version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current patch version of lipsum-cpp.
 */
inline constexpr int LIPSUM_CPP_VERSION_PATCH = 4;

/**
 * @brief The current Git commit of lipsum-cpp
 *
 * @since 0.4.2
 *
 * This constant stores the current abbreviated Git commit ID of lipsum-cpp
 * as of the last time scripts/version.cmake was ran.
 */
inline constexpr const char* LIPSUM_CPP_VERSION_COMMIT = "4e52ddd";

/**
 * @brief The current version of lipsum-cpp, to the Git commit.
 *
 * @since 0.4.2
 *
 * This constant stores the current version of lipsum-cpp with the abbreviated
 * Git commit ID as of the last time scripts/version.cmake was ran.
 */
inline constexpr const char* LIPSUM_CPP_VERSION_FULL = "0.4.4-4e52ddd";

#endif
