/**
 * @file lipsumc/version.h
 *
 * @brief Version macros for lipsum-cpp
 *
 * This defines macros for the current lipsum-cpp version. It is automatically
 * generated by a CMake script. This file is under the BSD Zero-Clause License.
 *
 * @copyright Copyright (c) 2026 LambBread
 *
 * @author LambBread from github.com
 */
#pragma once

#ifndef LIPSUMC_VERSION_H
#    define LIPSUMC_VERSION_H

// NOLINTBEGIN(modernize-macro-to-enum)

/**
 * @brief The current version of lipsum-cpp.
 *
 * @since 0.2.1
 *
 * This macro stores the current version of lipsum-cpp.
 */
#    define LIPSUM_CPP_VERSION_C "0.4.4"

/**
 * @brief The major version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This macro stores the current major version of lipsum-cpp.
 */
#    define LIPSUM_CPP_VERSION_MAJOR_C 0

/**
 * @brief The minor version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This macro stores the current minor version of lipsum-cpp.
 */
#    define LIPSUM_CPP_VERSION_MINOR_C 4

/**
 * @brief The patch version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This macro stores the current patch version of lipsum-cpp.
 */
#    define LIPSUM_CPP_VERSION_PATCH_C 4

/**
 * @brief The current Git commit of lipsum-cpp
 *
 * @since 0.4.2
 *
 * This macro stores the current abbreviated Git commit ID of lipsum-cpp
 * as of the last time scripts/version.cmake was ran.
 */
#    define LIPSUM_CPP_VERSION_COMMIT_C "2f3929a"

/**
 * @brief The current version of lipsum-cpp, to the Git commit.
 *
 * @since 0.4.2
 *
 * This macro stores the current version of lipsum-cpp with the abbreviated Git
 * commit ID as of the last time scripts/version.cmake was ran.
 */
#    define LIPSUM_CPP_VERSION_FULL_C "0.4.4-2f3929a"
// NOLINTEND(modernize-macro-to-enum)
#endif
