# this file runs in script mode, data passed with -D

message(STATUS "lipsum-cpp ---- creating version header files")

find_package(Git QUIET)
if(Git_FOUND)
    execute_process(
        COMMAND git rev-parse --short HEAD
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE LPSM_VERSION_COMMIT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE GIT_RESULT
    )
    if(NOT GIT_RESULT EQUAL 0)
        set(LPSM_VERSION_COMMIT "unknown")
    endif()
else()
    set(LPSM_VERSION_COMMIT "unknown")
endif()
message(STATUS "lipsum-cpp ---- current Git commit ${LPSM_VERSION_COMMIT}")


file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/src/lipsum/core/version.hpp
"/**
 * @file lipsum/core/version.hpp
 *
 * @brief Version constants for lipsum-cpp
 *
 * This defines constants for the current lipsum-cpp version. It is automatically generated by a CMake script.
 * This file is under the BSD Zero-Clause License.
 *
 * @copyright Copyright (c) 2026 LambBread
 *
 * @author LambBread from github.com
 */
#pragma once

#ifndef LIPSUM_CORE_VERSION_HPP
#define LIPSUM_CORE_VERSION_HPP

/**
 * @brief The current version of lipsum-cpp.
 *
 * @since 0.2.1
 *
 * This constant stores the current version of lipsum-cpp, stored as a string.
 */
inline constexpr const char* LIPSUM_CPP_VERSION = \"${LPSM_VERSION}\";

/**
 * @brief The current major version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current major version of lipsum-cpp.
 */
inline constexpr int LIPSUM_CPP_VERSION_MAJOR = ${LPSM_VERSION_MAJOR};

/**
 * @brief The current minor version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current minor version of lipsum-cpp.
 */
 inline constexpr int LIPSUM_CPP_VERSION_MINOR = ${LPSM_VERSION_MINOR};

/**
 * @brief The current patch version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current patch version of lipsum-cpp.
 */
 inline constexpr int LIPSUM_CPP_VERSION_PATCH = ${LPSM_VERSION_PATCH};

/**
* @brief The current Git commit of lipsum-cpp
*
* @since 0.4.2
*
* This constant stores the current abbreviated Git commit ID of lipsum-cpp
* as of the last time scripts/version.cmake was ran.
*/
inline constexpr const char* LIPSUM_CPP_VERSION_COMMIT = \"${LPSM_VERSION_COMMIT}\";

/**
* @brief The current version of lipsum-cpp, to the Git commit.
* 
* @since 0.4.2
*
* This constant stores the current version of lipsum-cpp with the abbreviated Git commit ID
* as of the last time scripts/version.cmake was ran.
*/
inline constexpr const char* LIPSUM_CPP_VERSION_FULL = \"${LPSM_VERSION}-${LPSM_VERSION_COMMIT}\";

#endif
")

file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/src/lipsumc/version.h
"/**
 * @file lipsumc/version.h
 *
 * @brief Version macros for lipsum-cpp
 *
 * This defines macros for the current lipsum-cpp version. It is automatically generated by a CMake script.
 * This file is under the BSD Zero-Clause License.
 *
 * @copyright Copyright (c) 2026 LambBread
 *
 * @author LambBread from github.com
 */
#pragma once

#ifndef LIPSUMC_VERSION_H
#define LIPSUMC_VERSION_H

//NOLINTBEGIN(modernize-macro-to-enum)

/**
 * @brief The current version of lipsum-cpp.
 *
 * @since 0.2.1
 *
 * This macro stores the current version of lipsum-cpp.
 */
 #define LIPSUM_CPP_VERSION_C \"${LPSM_VERSION}\"

/**
 * @brief The major version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This macro stores the current major version of lipsum-cpp.
 */
 #define LIPSUM_CPP_VERSION_MAJOR_C ${LPSM_VERSION_MAJOR}

/**
 * @brief The minor version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This macro stores the current minor version of lipsum-cpp.
 */
 #define LIPSUM_CPP_VERSION_MINOR_C ${LPSM_VERSION_MINOR}

/**
 * @brief The patch version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This macro stores the current patch version of lipsum-cpp.
 */
 #define LIPSUM_CPP_VERSION_PATCH_C ${LPSM_VERSION_PATCH}

/**
* @brief The current Git commit of lipsum-cpp
*
* @since 0.4.2
*
* This macro stores the current abbreviated Git commit ID of lipsum-cpp 
* as of the last time scripts/version.cmake was ran.
*/
#define LIPSUM_CPP_VERSION_COMMIT_C \"${LPSM_VERSION_COMMIT}\"

/**
* @brief The current version of lipsum-cpp, to the Git commit.
* 
* @since 0.4.2
*
* This macro stores the current version of lipsum-cpp with the abbreviated Git commit ID
* as of the last time scripts/version.cmake was ran.
*/
#define LIPSUM_CPP_VERSION_FULL_C \"${LPSM_VERSION}-${LPSM_VERSION_COMMIT}\"
//NOLINTEND(modernize-macro-to-enum)
 #endif
 ")

 file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile
"PROJECT_NAME = \"lipsum-cpp\"
PROJECT_BRIEF = \"A library written in C++ for generating sample text.\"
PROJECT_NUMBER = \"${LPSM_VERSION}\"
INPUT = src
EXAMPLE_PATH = examples/
RECURSIVE = YES
GENERATE_LATEX = NO
OUTPUT_DIRECTORY = docs
ALIASES += \"xovload=This function only differs from the function of the similar name in that it uses minimum and maximum values instead of lipsum::ArgVec2.\"
ALIASES += \"sovload=This function only differs from the function of the similar name in that it uses lpsm_ArgVec2Handle instead of separate minimum and maximum arguments. The arguments must be allocated with function lpsm_ArgVec2(), and deallocation is handled automatically if argument del is true.\"
WARN_IF_UNDOCUMENTED = NO
WARN_NO_PARAMDOC = YES
WARN_IF_DOC_ERROR = YES
QUIET = YES
WARNINGS = YES
")
