# this file runs in script mode, data passed with -D

message(STATUS "lipsum-cpp ---- creating version header files")

find_package(Git QUIET)
if(Git_FOUND)
    execute_process(
        COMMAND git rev-parse --short HEAD
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE LPSM_VERSION_COMMIT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE GIT_RESULT
    )
    if(NOT GIT_RESULT EQUAL 0)
        set(LPSM_VERSION_COMMIT "unknown")
        set(LPSM_VERSION_LASTPUSH)
    endif()
else()
    set(LPSM_VERSION_COMMIT "unknown")
endif()

set(LIPSUM_CPP_VERSION "${LPSM_VERSION}")
set(LIPSUM_CPP_VERSION_ISDEV "false")

if(LPSM_VERSION_DEV)
    string(APPEND LIPSUM_CPP_VERSION "-dev")
    set(LIPSUM_CPP_VERSION_ISDEV "true")
endif()

message(STATUS "lipsum-cpp ---- current Git commit ${LPSM_VERSION_COMMIT}")

string(TIMESTAMP LPSM_NOW "%Y-%m-%d %H:%M:%S UTC" UTC)
string(TIMESTAMP LPSM_DATE_NOW "%y%m%d%H" UTC)
message(STATUS "lipsum-cpp ---- current time ${LPSM_NOW}")
message(STATUS "lipsum-cpp ---- date ${LPSM_DATE_NOW}")

file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/PKGBUILD"
"# Maintainer: LambBread <LambBread@github.com>
pkgname=lipsum-cpp
pkgver=${LPSM_VERSION}
pkgrel=1
pkgdesc=${PROJECT_DESCRIPTION}
arch=('x86_64' 'aarch64')
url=\"https://github.com/LambBread/lipsum-cpp\"
license=('0BSD')
depends=()
makedepends=('cmake' 'base-devel' 'doxygen')
provides=('lipsum-cpp')
source=(\"\${pkgname}-master.tar.gz::https://github.com/LambBread/\${pkgname}/archive/master.tar.gz\")
sha256sums=('SKIP')

build() {
    cd \"\${pkgname}-master\"
    cmake -S . -B build \\
        -DLPSM_FORMAT=OFF -DLPSM_BUILD_VERSION=OFF -DLPSM_BUILD_SAMPLE=OFF \\
        -DLPSM_BUILD_DOCS=ON -DLPSM_BUILD_STATIC=ON \\
        -DLPSM_BUILD_CWRAPPER=ON -DLPSM_BUILD_CLI=ON \\
        -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    cmake --build build
} 

package() {
    cd \"\${pkgname}-master\"
    DESTDIR=\"\${pkgdir}\" cmake --install build
} 
")

file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/src/lipsum/core/version.hpp"
"/**
 * @file lipsum/core/version.hpp
 *
 * @brief Version constants for lipsum-cpp
 *
 * This defines constants for the current lipsum-cpp version. It is automatically generated by a CMake script.
 * This file is under the BSD Zero-Clause License.
 *
 * @copyright Copyright (c) 2026 LambBread
 *
 * @author LambBread from github.com
 */
#pragma once

#ifndef LIPSUM_CORE_VERSION_HPP
#define LIPSUM_CORE_VERSION_HPP

/**
 * @brief The current version of lipsum-cpp.
 *
 * @since 0.2.1
 *
 * This constant stores the current version of lipsum-cpp, stored as a string.
 */
 inline constexpr const char* LIPSUM_CPP_VERSION = \"${LIPSUM_CPP_VERSION}\";

/**
 * @brief The current major version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current major version of lipsum-cpp.
 */
inline constexpr int LIPSUM_CPP_VERSION_MAJOR = ${LPSM_VERSION_MAJOR};

/**
 * @brief The current minor version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current minor version of lipsum-cpp.
 */
 inline constexpr int LIPSUM_CPP_VERSION_MINOR = ${LPSM_VERSION_MINOR};

/**
 * @brief The current patch version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This constant stores the current patch version of lipsum-cpp.
 */
 inline constexpr int LIPSUM_CPP_VERSION_PATCH = ${LPSM_VERSION_PATCH};

/**
* @brief The current Git commit of lipsum-cpp
*
* @since 0.4.2
*
* This constant stores the current abbreviated Git commit ID of lipsum-cpp
* as of the last time scripts/version.cmake was ran.
*/
inline constexpr const char* LIPSUM_CPP_VERSION_COMMIT = \"${LPSM_VERSION_COMMIT}\";

/**
* @brief The current version of lipsum-cpp, to the Git commit.
* 
* @since 0.4.2
*
* This constant stores the current version of lipsum-cpp with the abbreviated Git commit ID and date
* as of the last time scripts/version.cmake was ran.
*/
inline constexpr const char* LIPSUM_CPP_VERSION_FULL = \"${LIPSUM_CPP_VERSION}+${LPSM_VERSION_COMMIT}-${LPSM_DATE_NOW}\";

/**
* @brief The time lipsum-cpp was last edited.
*
* @since 0.4.6
*
* This constant stores the current time in UTC as of the last time scripts/version.cmake was ran,
* in the format YYYY-MM-DD HH:MM:SS UTC.
*/
inline constexpr const char* LIPSUM_CPP_VERSION_TIME = \"${LPSM_NOW}\";

/**
* @brief Whether lipsum-cpp is a development build.
*
* @since 0.4.6
*
* This constant stores whether lipsum-cpp is a development build as of the last time scripts/version.cmake was ran.
*/
inline constexpr bool LIPSUM_CPP_VERSION_ISDEV = ${LIPSUM_CPP_VERSION_ISDEV};

/**
* @brief The date lipsum-cpp was last edited.
* 
* @since 0.4.6
*
* This constant stores the current date in UTC as of the last time scripts/version.cmake was ran, in the format
* YYMMDDHH.
*/
inline constexpr const char* LIPSUM_CPP_VERSION_DATE = \"${LPSM_DATE_NOW}\";
#endif
")

file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/src/lipsumc/version.h
"/**
 * @file lipsumc/version.h
 *
 * @brief Version macros for lipsum-cpp
 *
 * This defines macros for the current lipsum-cpp version. It is automatically generated by a CMake script.
 * This file is under the BSD Zero-Clause License.
 *
 * @copyright Copyright (c) 2026 LambBread
 *
 * @author LambBread from github.com
 */
#pragma once

#ifndef LIPSUMC_VERSION_H
#define LIPSUMC_VERSION_H

//NOLINTBEGIN(modernize-macro-to-enum)

/**
 * @brief The current version of lipsum-cpp.
 *
 * @since 0.2.1
 *
 * This macro stores the current version of lipsum-cpp.
 */
 #define LIPSUM_CPP_VERSION_C \"${LIPSUM_CPP_VERSION}\"

/**
 * @brief The major version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This macro stores the current major version of lipsum-cpp.
 */
 #define LIPSUM_CPP_VERSION_MAJOR_C ${LPSM_VERSION_MAJOR}

/**
 * @brief The minor version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This macro stores the current minor version of lipsum-cpp.
 */
 #define LIPSUM_CPP_VERSION_MINOR_C ${LPSM_VERSION_MINOR}

/**
 * @brief The patch version of lipsum-cpp.
 *
 * @since 0.4.0
 *
 * This macro stores the current patch version of lipsum-cpp.
 */
 #define LIPSUM_CPP_VERSION_PATCH_C ${LPSM_VERSION_PATCH}

/**
* @brief The current Git commit of lipsum-cpp
*
* @since 0.4.2
*
* This macro stores the current abbreviated Git commit ID of lipsum-cpp 
* as of the last time scripts/version.cmake was ran.
*/
#define LIPSUM_CPP_VERSION_COMMIT_C \"${LPSM_VERSION_COMMIT}\"

/**
* @brief The current version of lipsum-cpp, to the Git commit.
* 
* @since 0.4.2
*
* This macro stores the current version of lipsum-cpp with the abbreviated Git commit ID and date
* as of the last time scripts/version.cmake was ran.
*/
#define LIPSUM_CPP_VERSION_FULL_C \"${LIPSUM_CPP_VERSION}+${LPSM_VERSION_COMMIT}-${LPSM_DATE_NOW}\"

/**
* @brief The time lipsum-cpp was last edited.
*
* @since 0.4.6
*
* This macro stores the current time in UTC as of the last time scripts/version.cmake was ran,
* in the format YYYY-MM-DD HH:MM:SS UTC.
*/
#define LIPSUM_CPP_VERSION_TIME_C \"${LPSM_NOW}\"

/**
* @brief Whether lipsum-cpp is a development build.
*
* @since 0.4.6
*
* This macro stores whether lipsum-cpp is a development build as of the last time scripts/version.cmake was ran.
*/
#define LIPSUM_CPP_VERSION_ISDEV_C ${LIPSUM_CPP_VERSION_ISDEV}

/**
* @brief The date lipsum-cpp was last edited.
* 
* @since 0.4.6
*
* This macro stores the current date in UTC as of the last time scripts/version.cmake was ran, in the format
* YYMMDDHH.
*/
#define LIPSUM_CPP_VERSION_DATE_C \"${LPSM_DATE_NOW}\"

//NOLINTEND(modernize-macro-to-enum)
 #endif
 ")

 file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile
"PROJECT_NAME = \"lipsum-cpp\"
PROJECT_BRIEF = \"A library written in C++ for generating sample text.\"
PROJECT_NUMBER = \"${LPSM_VERSION}\"
INPUT = src
EXAMPLE_PATH = examples/
RECURSIVE = YES
GENERATE_LATEX = NO
OUTPUT_DIRECTORY = docs
WARN_IF_UNDOCUMENTED = NO
WARN_NO_PARAMDOC = YES
WARN_IF_DOC_ERROR = YES
QUIET = YES
WARNINGS = YES
EXTRACT_PRIVATE = YES
")
