if(LPSM_BUILD_VERSION)

add_custom_target(version
    COMMAND ${CMAKE_COMMAND} 
    -DLPSM_VERSION=${PROJECT_VERSION} 
    -DLPSM_VERSION_MAJOR=${PROJECT_VERSION_MAJOR} 
    -DLPSM_VERSION_MINOR=${PROJECT_VERSION_MINOR} 
    -DLPSM_VERSION_PATCH=${PROJECT_VERSION_PATCH} 
    -DLPSM_VERSION_DEV=${LPSM_VERSION_DEV}
    -DPROJECT_DESCRIPTION="${PROJECT_DESCRIPTION}"
    -P ${CMAKE_CURRENT_SOURCE_DIR}/scripts/version.cmake
    WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
    VERBATIM
)

endif()
