name: Build and package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.6'

      - name: Setup RPM packaging
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Build static library
        run: |
          cmake -S . -B build -DLPSM_BUILD_STATIC=ON -DLPSM_BUILD_CWRAPPER=ON -DLPSM_BUILD_EXAMPLES=ON -DLPSM_FORMAT=OFF -DLPSM_BUILD_SAMPLE=OFF -DLPSM_BUILD_VERSION=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Package with CPack
        run: |
          cd build
          cpack

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: lipsum-cpp-packages
          path: |
            build/*.zip
            build/*.tar.gz
            build/*.deb
            build/*.dmg
            build/*.rpm
            build/*.msi
          if-no-files-found: ignore
